# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('email_subs', models.EmailField(blank=True, max_length=254, unique=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('facebook_id', models.BigIntegerField(blank=True)),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('last_login', models.DateTimeField(verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
