# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 14:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_auto_20160808_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='facebook_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
